name: drone
services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    restart: unless-stopped
    environment:
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=https
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_DATABASE_DATASOURCE=/data/database.sqlite
      - DRONE_USER_CREATE=username:${GITHUB_USERNAME},admin:true
      - DRONE_USER_FILTER=${GITHUB_USERNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drone.rule=Host(`${DRONE_SERVER_HOST}`)"
      - "traefik.http.routers.drone.entrypoints=web"
      - "traefik.http.services.drone.loadbalancer.server.port=80"
    volumes:
      - drone-data:/data
    networks:
      - proxy
  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    restart: unless-stopped
    environment:
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NETWORKS=proxy
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
  drone-server-backup-prepare:
    image: alpine:latest
    container_name: drone-server-backup-prepare
    restart: unless-stopped
    volumes:
      - drone-data:/data
      - drone-data-backup:/dumps
    entrypoint: sh -c "apk add sqlite && echo '30 1 * * * sqlite3 /data/database.sqlite \".backup /dumps/database-backup.sqlite\"' | crontab - && crond -f -l 2"
  drone-server-backup:
    image: mazzolino/restic:latest
    container_name: drone-server-backup
    restart: unless-stopped
    environment:
      - BACKUP_CRON=0 2 * * *
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}/drone
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - RESTIC_BACKUP_ARGS=--verbose --tag drone
      - RESTIC_FORGET_ARGS=--keep-daily 7 --keep-weekly 4 --keep-monthly 6 --prune
      - TZ=Europe/Warsaw
    volumes:
      - drone-data-backup:/data/dumps:ro
      - ./:/data/compose:ro
    depends_on:
      - drone-server-backup-prepare
networks:
  proxy:
    external: true
volumes:
  drone-data:
  drone-data-backup:
