services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run homelab
    volumes:
      - /home/homelab/.cloudflared/cert.pem:/etc/cloudflared/cert.pem:ro
      - /home/homelab/.cloudflared/config.yml:/etc/cloudflared/config.yml:ro
      - /home/homelab/.cloudflared/${TUNNEL_ID}.json:/etc/cloudflared/${TUNNEL_ID}.json:ro
    networks:
      - proxy
networks:
  proxy:
    external: true
